var ohCrime2018 = {
    "type": "FeaturesCollection",
    "features":
[
    {
      "county": 'Allen',
      "murderAndNonnegligentManslaughter": 1,
      "robbery": 15,
      "aggravatedAssault": 9,
      "propertyCrime": 803,
      "burglary": 139,
      "burglary": 637,
      "motorVehicleTheft": 27,
      "arson": 2
    },
    {
      "county": 'Belmont',
      "violentCrime": 52,
      "murderAndNonnegligentManslaughter": 2,
      "rape": 19,
      "robbery": 3,
      "aggravatedAssault": 28,
      "propertyCrime": 217,
      "burglary": 41,
      "burglary": 165,
      "motorVehicleTheft": 11,
      "arson": 2
    },
    {
      "county": 'Clark',
      "violentCrime": 38,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 4,
      "robbery": 9,
      "aggravatedAssault": 25,
      "propertyCrime": 630,
      "burglary": 148,
      "burglary": 470,
      "motorVehicleTheft": 12,
      "arson": 1
    },
    {
      "county": 'Clermont',
      "violentCrime": 103,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 25,
      "robbery": 8,
      "aggravatedAssault": 70,
      "propertyCrime": 948,
      "burglary": 214,
      "burglary": 671,
      "motorVehicleTheft": 63,
      "arson": 2
    },
    {
      "county": 'Delaware',
      "violentCrime": 60,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 25,
      "robbery": 6,
      "aggravatedAssault": 29,
      "propertyCrime": 1096,
      "burglary": 174,
      "burglary": 884,
      "motorVehicleTheft": 38,
      "arson": 1
    },
    {
      "county": 'Fairfield',
      "violentCrime": 46,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 13,
      "robbery": 6,
      "aggravatedAssault": 27,
      "propertyCrime": 1071,
      "burglary": 149,
      "burglary": 881,
      "motorVehicleTheft": 41,
      "arson": 3
    },
    {
      "county": 'Fulton',
      "violentCrime": 15,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 4,
      "robbery": 3,
      "aggravatedAssault": 8,
      "propertyCrime": 222,
      "burglary": 59,
      "burglary": 163,
      "motorVehicleTheft": 0,
      "arson": 0
    },
    {
      "county": 'Geauga',
      "violentCrime": 21,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 3,
      "robbery": 1,
      "aggravatedAssault": 17,
      "propertyCrime": 117,
      "burglary": 23,
      "burglary": 91,
      "motorVehicleTheft": 3,
      "arson": 2
    },
    {
      "county": 'Greene',
      "violentCrime": 43,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 10,
      "robbery": 2,
      "aggravatedAssault": 31,
      "propertyCrime": 306,
      "burglary": 60,
      "burglary": 230,
      "motorVehicleTheft": 16,
      "arson": 1
    },
    {
      "county": 'Hamilton',
      "violentCrime": 168,
      "murderAndNonnegligentManslaughter": 3,
      "rape": 50,
      "robbery": 31,
      "aggravatedAssault": 84,
      "propertyCrime": 1933,
      "burglary": 232,
      "burglary": 1535,
      "motorVehicleTheft": 166,
      "arson": 14
    },
    {
      "county": 'Hocking',
      "violentCrime": 19,
      "murderAndNonnegligentManslaughter": 4,
      "rape": 2,
      "robbery": 1,
      "aggravatedAssault": 12,
      "propertyCrime": 495,
      "burglary": 112,
      "burglary": 246,
      "motorVehicleTheft": 137,
      "arson": 3
    },
    {
      "county": 'Jefferson',
      "violentCrime": 12,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 1,
      "robbery": 0,
      "aggravatedAssault": 11,
      "propertyCrime": 75,
      "burglary": 25,
      "burglary": 43,
      "motorVehicleTheft": 7,
      "arson": 1
    },
    {
      "county": 'Lake',
      "murderAndNonnegligentManslaughter": 3,
      "robbery": 5,
      "aggravatedAssault": 182,
      "propertyCrime": 305,
      "burglary": 82,
      "burglary": 218,
      "motorVehicleTheft": 5,
      "arson": 0
    },
    {
      "county": 'Lawrence',
      "violentCrime": 56,
      "murderAndNonnegligentManslaughter": 1,
      "rape": 13,
      "robbery": 4,
      "aggravatedAssault": 38,
      "propertyCrime": 510,
      "burglary": 145,
      "burglary": 315,
      "motorVehicleTheft": 50,
      "arson": 2
    },
    {
      "county": 'Lorain',
      "violentCrime": 76,
      "murderAndNonnegligentManslaughter": 2,
      "rape": 18,
      "robbery": 12,
      "aggravatedAssault": 44,
      "propertyCrime": 460,
      "burglary": 164,
      "burglary": 274,
      "motorVehicleTheft": 22,
      "arson": 5
    },
    {
      "county": 'Lucas',
      "violentCrime": 104,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 31,
      "robbery": 30,
      "aggravatedAssault": 43,
      "propertyCrime": 950,
      "burglary": 155,
      "burglary": 729,
      "motorVehicleTheft": 66,
      "arson": 4
    },
    {
      "county": 'Madison',
      "violentCrime": 13,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 1,
      "robbery": 4,
      "aggravatedAssault": 8,
      "propertyCrime": 334,
      "burglary": 83,
      "burglary": 234,
      "motorVehicleTheft": 17,
      "arson": 2
    },
    {
      "county": 'Mahoning',
      "violentCrime": 4,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 1,
      "robbery": 1,
      "aggravatedAssault": 2,
      "propertyCrime": 81,
      "burglary": 5,
      "burglary": 72,
      "motorVehicleTheft": 4,
      "arson": 0
    },
    {
      "county": 'Medina',
      "violentCrime": 5,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 0,
      "robbery": 1,
      "aggravatedAssault": 4,
      "propertyCrime": 86,
      "burglary": 23,
      "burglary": 63,
      "motorVehicleTheft": 0,
      "arson": 0
    },
    {
      "county": 'Miami',
      "violentCrime": 35,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 11,
      "robbery": 0,
      "aggravatedAssault": 24,
      "propertyCrime": 321,
      "burglary": 78,
      "burglary": 212,
      "motorVehicleTheft": 31,
      "arson": 8
    },
    {
      "county": 'Montgomery',
      "violentCrime": 269,
      "murderAndNonnegligentManslaughter": 7,
      "rape": 42,
      "robbery": 67,
      "aggravatedAssault": 153,
      "propertyCrime": 1266,
      "burglary": 282,
      "burglary": 663,
      "motorVehicleTheft": 321,
      "arson": 9
    },
    {
      "county": 'Perry',
      "violentCrime": 6,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 2,
      "robbery": 0,
      "aggravatedAssault": 4,
      "propertyCrime": 85,
      "burglary": 32,
      "burglary": 50,
      "motorVehicleTheft": 3,
      "arson": 0
    },
    {
      "county": 'Pickaway',
      "violentCrime": 31,
      "murderAndNonnegligentManslaughter": 1,
      "rape": 9,
      "robbery": 2,
      "aggravatedAssault": 19,
      "propertyCrime": 619,
      "burglary": 145,
      "burglary": 443,
      "motorVehicleTheft": 31,
      "arson": 4
    },
    {
      "county": 'Portage',
      "murderAndNonnegligentManslaughter": 1,
      "robbery": 13,
      "aggravatedAssault": 337,
      "propertyCrime": 991,
      "burglary": 217,
      "burglary": 731,
      "motorVehicleTheft": 43,
      "arson": 3
    },
    {
      "county": 'Richland',
      "violentCrime": 65,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 35,
      "robbery": 9,
      "aggravatedAssault": 21,
      "propertyCrime": 748,
      "burglary": 185,
      "burglary": 507,
      "motorVehicleTheft": 56,
      "arson": 4
    },
    {
      "county": 'Stark',
      "violentCrime": 116,
      "murderAndNonnegligentManslaughter": 1,
      "rape": 32,
      "robbery": 26,
      "aggravatedAssault": 57,
      "propertyCrime": 1578,
      "burglary": 422,
      "burglary": 1057,
      "motorVehicleTheft": 99,
      "arson": 11
    },
    {
      "county": 'Summit',
      "violentCrime": 70,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 26,
      "robbery": 12,
      "aggravatedAssault": 32,
      "propertyCrime": 889,
      "burglary": 129,
      "burglary": 712,
      "motorVehicleTheft": 48,
      "arson": 3
    },
    {
      "county": 'Trumbull',
      "violentCrime": 17,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 4,
      "robbery": 2,
      "aggravatedAssault": 11,
      "propertyCrime": 201,
      "burglary": 76,
      "burglary": 119,
      "motorVehicleTheft": 6,
      "arson": 0
    },
    {
      "county": 'Union',
      "violentCrime": 39,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 21,
      "robbery": 1,
      "aggravatedAssault": 17,
      "propertyCrime": 181,
      "burglary": 33,
      "burglary": 133,
      "motorVehicleTheft": 15,
      "arson": 0
    },
    {
      "county": 'Warren',
      "violentCrime": 51,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 10,
      "robbery": 4,
      "aggravatedAssault": 37,
      "propertyCrime": 741,
      "burglary": 96,
      "burglary": 586,
      "motorVehicleTheft": 59,
      "arson": 1
    },
    {
      "county": 'Wood',
      "violentCrime": 25,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 9,
      "robbery": 2,
      "aggravatedAssault": 14,
      "propertyCrime": 362,
      "burglary": 86,
      "burglary": 261,
      "motorVehicleTheft": 15,
      "arson": 2
    },
    {
      "county": 'Adams',
      "violentCrime": 11,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 5,
      "robbery": 0,
      "aggravatedAssault": 6,
      "propertyCrime": 196,
      "burglary": 79,
      "burglary": 100,
      "motorVehicleTheft": 17,
      "arson": 2
    },
    {
      "county": 'Ashland',
      "violentCrime": 18,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 13,
      "robbery": 0,
      "aggravatedAssault": 5,
      "propertyCrime": 144,
      "burglary": 47,
      "burglary": 93,
      "motorVehicleTheft": 4,
      "arson": 3
    },
    {
      "county": 'Ashtabula',
      "violentCrime": 45,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 6,
      "robbery": 8,
      "aggravatedAssault": 31,
      "propertyCrime": 479,
      "burglary": 113,
      "burglary": 327,
      "motorVehicleTheft": 39,
      "arson": 1
    },
    {
      "county": 'Athens',
      "violentCrime": 18,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 6,
      "robbery": 3,
      "aggravatedAssault": 9,
      "propertyCrime": 308,
      "burglary": 96,
      "burglary": 186,
      "motorVehicleTheft": 26,
      "arson": 0
    },
    {
      "county": 'Champaign',
      "violentCrime": 21,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 6,
      "robbery": 0,
      "aggravatedAssault": 15,
      "propertyCrime": 167,
      "burglary": 48,
      "burglary": 112,
      "motorVehicleTheft": 7,
      "arson": 2
    },
    {
      "county": 'Clinton',
      "violentCrime": 14,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 5,
      "robbery": 0,
      "aggravatedAssault": 9,
      "propertyCrime": 112,
      "burglary": 37,
      "burglary": 63,
      "motorVehicleTheft": 12,
      "arson": 1
    },
    {
      "county": 'Columbiana',
      "violentCrime": 28,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 4,
      "robbery": 4,
      "aggravatedAssault": 20,
      "propertyCrime": 326,
      "burglary": 90,
      "burglary": 208,
      "motorVehicleTheft": 28,
      "arson": 4
    },
    {
      "county": 'Coshocton',
      "violentCrime": 42,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 13,
      "robbery": 2,
      "aggravatedAssault": 27,
      "propertyCrime": 389,
      "burglary": 92,
      "burglary": 263,
      "motorVehicleTheft": 34,
      "arson": 3
    },
    {
      "county": 'Crawford',
      "violentCrime": 3,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 1,
      "robbery": 0,
      "aggravatedAssault": 2,
      "propertyCrime": 102,
      "burglary": 36,
      "burglary": 59,
      "motorVehicleTheft": 7,
      "arson": 0
    },
    {
      "county": 'Defiance',
      "violentCrime": 13,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 6,
      "robbery": 0,
      "aggravatedAssault": 7,
      "propertyCrime": 122,
      "burglary": 34,
      "burglary": 85,
      "motorVehicleTheft": 3,
      "arson": 2
    },
    {
      "county": 'Erie',
      "violentCrime": 5,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 0,
      "robbery": 0,
      "aggravatedAssault": 5,
      "propertyCrime": 202,
      "burglary": 45,
      "burglary": 151,
      "motorVehicleTheft": 6,
      "arson": 0
    },
    {
      "county": 'Fayette',
      "violentCrime": 39,
      "murderAndNonnegligentManslaughter": 2,
      "rape": 11,
      "robbery": 7,
      "aggravatedAssault": 19,
      "propertyCrime": 388,
      "burglary": 117,
      "burglary": 252,
      "motorVehicleTheft": 19,
      "arson": 2
    },
    {
      "county": 'Gallia',
      "violentCrime": 30,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 3,
      "robbery": 2,
      "aggravatedAssault": 25,
      "propertyCrime": 369,
      "burglary": 105,
      "burglary": 238,
      "motorVehicleTheft": 26,
      "arson": 4
    },
    {
      "county": 'Hancock',
      "violentCrime": 20,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 7,
      "robbery": 3,
      "aggravatedAssault": 10,
      "propertyCrime": 156,
      "burglary": 35,
      "burglary": 113,
      "motorVehicleTheft": 8,
      "arson": 1
    },
    {
      "county": 'Hardin',
      "violentCrime": 10,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 0,
      "robbery": 3,
      "aggravatedAssault": 7,
      "propertyCrime": 89,
      "burglary": 19,
      "burglary": 67,
      "motorVehicleTheft": 3,
      "arson": 4
    },
    {
      "county": 'Henry',
      "violentCrime": 15,
      "murderAndNonnegligentManslaughter": 1,
      "rape": 3,
      "robbery": 0,
      "aggravatedAssault": 11,
      "propertyCrime": 122,
      "burglary": 40,
      "burglary": 75,
      "motorVehicleTheft": 7,
      "arson": 1
    },
    {
      "county": 'Highland',
      "violentCrime": 20,
      "murderAndNonnegligentManslaughter": 2,
      "rape": 12,
      "robbery": 2,
      "aggravatedAssault": 4,
      "propertyCrime": 271,
      "burglary": 95,
      "burglary": 157,
      "motorVehicleTheft": 19,
      "arson": 1
    },
    {
      "county": 'Jackson',
      "violentCrime": 29,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 7,
      "robbery": 3,
      "aggravatedAssault": 19,
      "propertyCrime": 230,
      "burglary": 67,
      "burglary": 143,
      "motorVehicleTheft": 20,
      "arson": 0
    },
    {
      "county": 'Knox',
      "violentCrime": 51,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 21,
      "robbery": 2,
      "aggravatedAssault": 28,
      "propertyCrime": 333,
      "burglary": 94,
      "burglary": 239,
      "motorVehicleTheft": 0,
      "arson": 1
    },
    {
      "county": 'Logan',
      "violentCrime": 19,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 3,
      "robbery": 1,
      "aggravatedAssault": 15,
      "propertyCrime": 176,
      "burglary": 43,
      "burglary": 119,
      "motorVehicleTheft": 14,
      "arson": 1
    },
    {
      "county": 'Marion',
      "violentCrime": 36,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 16,
      "robbery": 7,
      "aggravatedAssault": 13,
      "propertyCrime": 888,
      "burglary": 122,
      "burglary": 742,
      "motorVehicleTheft": 24,
      "arson": 2
    },
    {
      "county": 'Meigs',
      "violentCrime": 17,
      "murderAndNonnegligentManslaughter": 1,
      "rape": 3,
      "robbery": 1,
      "aggravatedAssault": 12,
      "propertyCrime": 217,
      "burglary": 51,
      "burglary": 133,
      "motorVehicleTheft": 33,
      "arson": 4
    },
    {
      "county": 'Mercer',
      "violentCrime": 10,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 4,
      "robbery": 0,
      "aggravatedAssault": 6,
      "propertyCrime": 82,
      "burglary": 8,
      "burglary": 73,
      "motorVehicleTheft": 1,
      "arson": 0
    },
    {
      "county": 'Monroe',
      "violentCrime": 15,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 7,
      "robbery": 0,
      "aggravatedAssault": 8,
      "propertyCrime": 44,
      "burglary": 14,
      "burglary": 23,
      "motorVehicleTheft": 7,
      "arson": 1
    },
    {
      "county": 'Morgan',
      "violentCrime": 24,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 4,
      "robbery": 0,
      "aggravatedAssault": 20,
      "propertyCrime": 138,
      "burglary": 51,
      "burglary": 77,
      "motorVehicleTheft": 10,
      "arson": 2
    },
    {
      "county": 'Noble',
      "violentCrime": 1,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 1,
      "robbery": 0,
      "aggravatedAssault": 0,
      "propertyCrime": 38,
      "burglary": 12,
      "burglary": 25,
      "motorVehicleTheft": 1,
      "arson": 0
    },
    {
      "county": 'Pike',
      "violentCrime": 37,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 12,
      "robbery": 2,
      "aggravatedAssault": 23,
      "propertyCrime": 380,
      "burglary": 101,
      "burglary": 231,
      "motorVehicleTheft": 48,
      "arson": 5
    },
    {
      "county": 'Preble',
      "violentCrime": 14,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 2,
      "robbery": 0,
      "aggravatedAssault": 12,
      "propertyCrime": 207,
      "burglary": 38,
      "burglary": 135,
      "motorVehicleTheft": 34,
      "arson": 1
    },
    {
      "county": 'Putnam',
      "violentCrime": 10,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 1,
      "robbery": 0,
      "aggravatedAssault": 9,
      "propertyCrime": 75,
      "burglary": 10,
      "burglary": 65,
      "motorVehicleTheft": 0,
      "arson": 0
    },
    {
      "county": 'Ross',
      "violentCrime": 114,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 31,
      "robbery": 3,
      "aggravatedAssault": 80,
      "propertyCrime": 1071,
      "burglary": 270,
      "burglary": 676,
      "motorVehicleTheft": 125,
      "arson": 17
    },
    {
      "county": 'Scioto',
      "violentCrime": 58,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 12,
      "robbery": 13,
      "aggravatedAssault": 33,
      "propertyCrime": 882,
      "burglary": 240,
      "burglary": 539,
      "motorVehicleTheft": 103,
      "arson": 14
    },
    {
      "county": 'Shelby',
      "violentCrime": 14,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 6,
      "robbery": 1,
      "aggravatedAssault": 7,
      "propertyCrime": 120,
      "burglary": 14,
      "burglary": 96,
      "motorVehicleTheft": 10,
      "arson": 0
    },
    {
      "county": 'Tuscarawas',
      "violentCrime": 18,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 7,
      "robbery": 1,
      "aggravatedAssault": 10,
      "propertyCrime": 284,
      "burglary": 68,
      "burglary": 193,
      "motorVehicleTheft": 23,
      "arson": 2
    },
    {
      "county": 'Van Wert',
      "violentCrime": 25,
      "murderAndNonnegligentManslaughter": 1,
      "rape": 7,
      "robbery": 0,
      "aggravatedAssault": 17,
      "propertyCrime": 105,
      "burglary": 36,
      "burglary": 61,
      "motorVehicleTheft": 8,
      "arson": 1
    },
    {
      "county": 'Vinton',
      "violentCrime": 20,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 1,
      "robbery": 2,
      "aggravatedAssault": 17,
      "propertyCrime": 192,
      "burglary": 72,
      "burglary": 101,
      "motorVehicleTheft": 19,
      "arson": 0
    },
    {
      "county": 'Washington',
      "violentCrime": 31,
      "murderAndNonnegligentManslaughter": 0,
      "rape": 15,
      "robbery": 1,
      "aggravatedAssault": 15,
      "propertyCrime": 273,
      "burglary": 89,
      "burglary": 165,
      "motorVehicleTheft": 19,
      "arson": 2
    },
    {
      "county": 'Wayne',
      "violentCrime": 46,
      "murderAndNonnegligentManslaughter": 1,
      "rape": 13,
      "robbery": 2,
      "aggravatedAssault": 30,
      "propertyCrime": 478,
      "burglary": 149,
      "burglary": 281,
      "motorVehicleTheft": 48,
      "arson": 3
    },
    {
      "county": 'Wyandot',
      "violentCrime": 3,
      "murderAndNonnegligentManslaughter": 1,
      "rape": 0,
      "robbery": 0,
      "aggravatedAssault": 2,
      "propertyCrime": 1,
      "burglary": 0,
      "burglary": 1,
      "motorVehicleTheft": 0,
      "arson": 1
    }
  ]
}